/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [16-1:0] M_control_out;
  wire [1-1:0] M_control_z;
  wire [1-1:0] M_control_v;
  wire [1-1:0] M_control_n;
  wire [1-1:0] M_control_alufnexception;
  reg [1-1:0] M_control_write_b;
  reg [1-1:0] M_control_auto;
  reg [16-1:0] M_control_in;
  reg [6-1:0] M_control_alufn;
  control_1 control (
    .clk(clk),
    .rst(rst),
    .write_b(M_control_write_b),
    .auto(M_control_auto),
    .in(M_control_in),
    .alufn(M_control_alufn),
    .out(M_control_out),
    .z(M_control_z),
    .v(M_control_v),
    .n(M_control_n),
    .alufnexception(M_control_alufnexception)
  );
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    io_led[0+7-:8] = M_control_out[0+7-:8];
    io_led[8+7-:8] = M_control_out[8+7-:8];
    M_control_alufn = io_dip[16+1+5-:6];
    M_control_in[0+7-:8] = io_dip[0+7-:8];
    M_control_in[8+7-:8] = io_dip[8+7-:8];
    M_control_write_b = io_dip[16+0+0-:1];
    M_control_auto = io_button[0+0-:1];
    io_led[16+7+0-:1] = M_control_alufnexception;
  end
endmodule
