/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_7 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] alufn,
    output reg [15:0] s
  );
  
  
  
  integer i;
  
  reg [1:0] j;
  
  always @* begin
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      j[0+0-:1] = a[(i)*1+0-:1];
      j[1+0-:1] = b[(i)*1+0-:1];
      
      case (j)
        2'h0: begin
          s[(i)*1+0-:1] = alufn[0+0-:1];
        end
        2'h1: begin
          s[(i)*1+0-:1] = alufn[1+0-:1];
        end
        2'h2: begin
          s[(i)*1+0-:1] = alufn[2+0-:1];
        end
        2'h3: begin
          s[(i)*1+0-:1] = alufn[3+0-:1];
        end
        default: begin
          s[(i)*1+0-:1] = 1'h0;
        end
      endcase
    end
  end
endmodule
